Billennium-frontend-interns/linkedin_clone_project

- .gitignore
- README.md
- src/firebase.ts
- Firebase config with enviroment variables
- Create enviroment variables/ Update .gitignore/ Add firebase config
> Create enviroment variables/ Update .gitignore/ Add firebase config

- src/actions/logout.tsx
- src/actions/signout.tsx
- src/components/Dropdown/Dropdown.scss
- src/components/Dropdown/Dropdown.tsx
- src/components/DropdownsContent/HeaderDropdown.scss
- src/components/DropdownsContent/HeaderDropdown.tsx
- src/components/Header/Header.scss
- src/components/Header/Header.test.tsx
- src/components/Header/Header.tsx
- src/components/Navigation/Navigation.tsx
- src/components/NavigationIcon/NavigationIcon.scss
- src/components/NavigationIcon/NavigationIcon.tsx
- src/components/Search/Search.tsx
- src/constants/HeaderDropdown.tsx
- src/constants/Navigation.ts
- src/routes/DefaultRoute.tsx
- src/routes/Routes.tsx
- src/stories/Dropdown/Dropdown.stories.tsx
- src/styles/Colors.scss
- src/styles/ZIndexes.scss
- Add dropdown list in header &  Add tests for Header component
- I created Dropdown Component placed in the header, if you click on the avatar icon, the dropdown will appear and it will be displayed until we click somewhere else in the application. I also added very simple tests to the Header Component
- It's still a prototype, but I'm curious about the team's opinion because I don't know if it's a good way to build this Component, and in the future its contents will be changed to look better, now it only has an avatar name and two buttons. I am waiting for a lot of comments, I will read them when I am bored at work
- 
RIGHT NOW
> Add Dropdown component, add some very basic test to the Header component

- package-lock.json
- package.json
- src/App.tsx
- src/actions/customToast.tsx
- src/actions/followAction.tsx
- src/actions/setPost.tsx
- src/actions/signInWithCredentials.tsx
- src/actions/signInWithGooglePopup.tsx
- src/actions/signUpWithCredentails.tsx
- src/actions/signout.tsx
- src/components/DropdownsContent/HeaderDropdown.tsx
- src/components/UserCard/UserCard.tsx
- src/components/UserDetails/UserDetails.tsx
- src/constants/UserHints.ts
- src/pages/Feed/Feed.tsx
- src/pages/MyNetwork/MyNetwork.tsx
- src/pages/UserPage/UserPage.tsx
- src/pages/Welcome/Welcome.scss
- src/pages/Welcome/Welcome.tsx
- src/routes/Routes.tsx
- Add notifications after async operations
Added notifications after:
- sign in
- sign out
- sign up
- add post
- follow user
- unfollow user
- more appears after adding new functionalities
- The Feed page is a prototype added for testing purposes
> Add notifications to adding post, singIn signOut etc..

- src/components/GlobalErrorBoundary/GlobalErrorBoundary.tsx
- src/index.tsx
- src/pages/ErrorFallback/ErrorFallback.scss
- src/pages/ErrorFallback/ErrorFallback.tsx
- Global Error Boundary
- Add Global Error Boundary
- No additional information
- When there is an error (User can click refresh icon to reload page)
> Add GlobalErrorBoundary

- src/components/RecommendedUsers/RecommendedUsers.tsx
- Fix expand button
- Expand button  now disappear when there are no more users
- there are not any additional information or context
> Fix expand button

- src/components/Dropdown/Dropdown.tsx
- src/components/Header/Header.tsx
- src/components/Search/Search.tsx
- Logo not redirect to feed pag
- Right now logo redirect to feed page
- There are not any additional information or context
- No screenshots : (
> Change logo in header to link,fix some types

- src/components/CreatePost/CreatePost.scss
- Create post border radius isnt changed on mobile
- There are not any detailed information of applied changes
- There are not any additional information or context
> Remove border radius at mobile in CreatePost

- src/components/EditProfile/EditProfile.tsx
- src/components/EditProfileForm/EditProfileForm.tsx
- Improve EditProfile Modal
- EditProfile Modal now closing after editing
- No additional info
> Improve EditProfile Modal

- src/components/Notification/Notification.tsx
- src/components/UserCard/UserCard.scss
- src/components/UserCard/UserCard.tsx
- src/shared/interfaces/UserInterfaces.tsx
- Add hover at notification, fix link in notification and userCard in MyNetwork | Add Clicked button effect at Network
- Add detailed information of applied changes
> Change buttons, fix links

- src/actions/useGetUserData.tsx
- src/components/EditProfileForm/EditProfileForm.tsx
- src/components/UserDetails/UserDetails.tsx
- src/pages/UserPage/UserPage.tsx
- src/shared/interfaces/UserInterfaces.tsx
- src/stories/UserPage/UserDetails.stories.tsx
- Replace bio with headline
- Replace bio with headline at user profile
- No additional information
- No  Screenshots
> Replace bio with headline

- src/components/CreatePost/CreatePost.tsx
- src/components/FeedPost/FeedPost.scss
- src/components/UserPageField/UserPageField.scss
- src/components/UserPageFieldForm/UserPageFieldForm.tsx
- Bug fixes
- Changed word wrapping and input lengths
> fix wrap, input length bugs

- src/components/DropdownsContent/HeaderDropdown.scss
- src/components/DropdownsContent/HeaderDropdown.tsx
- src/components/Search/Search.tsx
- src/components/SearchHint/SearchHint.tsx
- src/constants/UserHints.ts
- src/shared/interfaces/UserInterfaces.tsx
- src/stories/SearchHint/SearchHint.stories.tsx
- Add headline
- Headline is now visible in search hints and dropdown
> Add headline to dropdown and search hints

- src/components/DropdownsContent/HeaderDropdown.scss
- Center headline text
- Center headline text
- 
- No additional info
> Center headline text

- src/actions/signUpWithCredentails.tsx
- Fix SignUp
- Fix SignUp
- No additional information 
> Fix SignUp

- src/components/CreatePost/CreatePost.scss
- src/components/CreatePost/CreatePost.tsx
- src/components/DropdownsContent/HeaderDropdown.scss
- src/components/DropdownsContent/HeaderDropdown.tsx
- Add post avatar aligment
- Aligment createPost, add loeader to dropdown
> Aligment createPost, add loeader to dropdown

- src/components/EditProfile/EditProfile.scss
- src/components/EditProfile/EditProfile.tsx
- Replace Close Button with CloseIcon
- Replace Close Button with CloseIcon
- No additional information or context
> Replace Close Button with CloseIcon

- src/components/MyPosts/MyPosts.scss
- src/components/MyPosts/MyPosts.tsx
- src/pages/UserPage/UserPage.scss
- src/pages/UserPage/UserPage.tsx
- Add MyPosts Component and Connect to UserPage
- Add MyPost component to display user posts
- Connect MyPost component to UserPage
- Add switch button at User Page to switch beetwen User Fields/User Posts
- I don't know if See My Posts / Show profile fields button looks good it would be nice if you tell me
- Switch button
- More posts
- No more posts
> Add MyPosts Component and Connect to UserPage

- cypress/integration/smoke-tests.ts
- cypress/support/commands.ts
- package.json
- Provide task name
- Add detailed information of applied changes
> Add smoke tests

- src/components/Header/Header.scss
- src/components/NavigationIcon/NavigationIcon.scss
- src/components/Search/Search.scss
- src/components/SearchHint/SearchHint.scss
- src/styles/FontSizes.scss
- Search Fix
- Search now has a fixed length and does not change depending on the hints
> Change search width

- src/components/FeedPost/FeedPost.scss
- src/components/FeedPost/FeedPost.tsx
- src/components/FollowedUsers/FollowedUsers.tsx
- src/components/RecommendedUsers/RecommendedUsers.tsx
- src/components/UserCard/UserCard.scss
- src/components/UserCard/UserCard.tsx
- Add headline
- Headline is now visible in FeedPost and UserCard
- 
> Add headline to FeedPost and UserCard

- src/components/EditProfile/EditProfile.scss
- src/components/EditProfile/EditProfile.tsx
- Fix button width
- Fix button width
- No additional info
> Fix button width

- src/actions/updateProfileFields.tsx
- src/components/UserPageField/UserPageField.tsx
- src/pages/UserPage/UserPage.tsx
- src/shared/interfaces/ProfileFieldInterfaces.tsx
- Fix delete icon visible on other user profiles
- Fix delete icon visible on other user profiles
- No additional information
> Fix delete icon visible on other user profiles

- src/components/Dropdown/Dropdown.scss
- src/components/Notification/Notification.scss
- src/components/Search/Search.scss
- src/styles/Colors.scss
- change notifications hover and search color
- change search color
- change hover
**Before**
Search
Notification
**After**
Search
Notification
> change hover & color search
